// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/alerts" | "/admin/analytics" | "/admin/customers" | "/admin/discounts" | "/admin/expenses" | "/admin/inventory" | "/admin/messages" | "/admin/orders" | "/admin/products" | "/admin/waitlist" | "/app" | "/careers" | "/cart" | "/collections/all" | "/collections/best-sellers" | "/collections/men" | "/collections/new-arrivals" | "/collections/women" | "/contact" | "/faq" | "/impact" | "/privacy" | "/products/[slug]" | "/returns" | "/shipping" | "/shop" | "/size-guide" | "/terms"
type AppRouteHandlerRoutes = "/api/admin/cleanup" | "/api/auth/session" | "/api/contact" | "/api/csrf" | "/api/geo" | "/api/health" | "/api/orders/create" | "/api/orders/validate" | "/api/products" | "/api/waitlist"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/app" | "/careers" | "/cart" | "/contact" | "/faq" | "/impact" | "/shop" | "/size-guide"
type RedirectRoutes = "/shop"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/alerts": {}
  "/admin/analytics": {}
  "/admin/customers": {}
  "/admin/discounts": {}
  "/admin/expenses": {}
  "/admin/inventory": {}
  "/admin/messages": {}
  "/admin/orders": {}
  "/admin/products": {}
  "/admin/waitlist": {}
  "/api/admin/cleanup": {}
  "/api/auth/session": {}
  "/api/contact": {}
  "/api/csrf": {}
  "/api/geo": {}
  "/api/health": {}
  "/api/orders/create": {}
  "/api/orders/validate": {}
  "/api/products": {}
  "/api/waitlist": {}
  "/app": {}
  "/careers": {}
  "/cart": {}
  "/collections/all": {}
  "/collections/best-sellers": {}
  "/collections/men": {}
  "/collections/new-arrivals": {}
  "/collections/women": {}
  "/contact": {}
  "/faq": {}
  "/impact": {}
  "/privacy": {}
  "/products/[slug]": { "slug": string; }
  "/returns": {}
  "/shipping": {}
  "/shop": {}
  "/size-guide": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/app": never
  "/careers": never
  "/cart": never
  "/contact": never
  "/faq": never
  "/impact": never
  "/shop": never
  "/size-guide": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
