var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/waitlist/route.js")
R.c("server/chunks/[root-of-the-server]__b9b9d8a7._.js")
R.c("server/chunks/[root-of-the-server]__d31f3393._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__2ea259cf._.js")
R.c("server/chunks/[root-of-the-server]__2501908c._.js")
R.c("server/chunks/_next-internal_server_app_api_waitlist_route_actions_b2a1061a.js")
R.m(64879)
module.exports=R.m(64879).exports
